module Instructions where

import qualified Data.ByteString.Lazy as B

data Instruction = Instruction
    { operation :: Operation
    , input     :: [Int]
    } deriving (Show)

data Operation = AALOAD
               | AASTORE
               | ACONST_NULL
               | ALOAD
               | ALOAD_N
               | ANEWARRAY
               | ARETURN
               | ARRAYLENGTH
               | ASTORE
               | ASTORE_N
               | ATHROW
               | BALOAD
               | BASTORE
               | BIPUSH
               | CALOAD
               | CASTORE
               | CHECKCAST
               | D2I
               | D2F
               | D2L
               | DADD
               | DALOAD
               | DASTORE
               | DCMPOP
               | DCONST_D
               | DDIV
               | DLOAD
               | DLOAD_N
               | DMUL
               | DNEQ
               | DREM
               | DRETURN
               | DSTORE
               | DSTORE_N
               | DSUB
               | DUP
               | DUP_X1
               | DUP_X2
               | DUP2
               | DUP2_X1
               | DUP2_X2
               | F2D
               | F2I
               | F2L
               | FADD
               | FALOAD
               | FASTORE
               | FCMPOP
               | FCONST_F
               | FDIV
               | FLOAD
               | FLOAD_N
               | FMUL
               | FNEQ
               | FREM
               | FRETURN
               | FSTORE
               | FSTORE_N
               | FSUB
               | GETFIELD
               | GETSTATIC
               | GOTO
               | GOTO_W
               | I2B
               | I2C
               | I2D
               | I2F
               | I2L
               | I2S
               | IADD
               | IALOAD
               | IAND
               | IASTORE
               | ICONST_I
               | IDIV
               | IF_ACMP_COND
               | IF_ICMP_COND
               | IF_COND
               | IFNONNULL
               | IFNULL
               | IINC
               | ILOAD
               | ILOAD_N
               | IMUL
               | INEQ
               | INSTANCEOF
               | INVOKEDYNAMIC
               | INVOKEINTERFACE
               | INVOKESPECIAL
               | INVOKESTATIC
               | INVOKEVIRTUAL
               | IOR
               | IREM
               | IRETURN
               | ISHL
               | ISHR
               | ISTORE
               | ISTORE_N
               | ISUB
               | IUSHR
               | IXOR
               | JSR
               | JSR_W
               | L2D
               | L2F
               | L2I
               | LADD
               | LALOAD
               | LAND
               | LASTORE
               | LCMP
               | LCONST_L
               | LDC
               | LDC_W
               | LDC2_W
               | LDIV
               | LLOAD
               | LLOAD_N
               | LMUL
               | LNEQ
               | LOOKUPSWITCH
               | LOR
               | LREM
               | LRETURN
               | LSHL
               | LSHR
               | LSTORE
               | LSTORE_N
               | LSUB
               | LUSHR
               | LXOR
               | MONITORENTER
               | MONITOREXIT
               | MULTIANEWARRAY
               | NEW
               | NEWARRAY
               | NOP
               | POP
               | POP2
               | PUTFIELD
               | PUTSTATIC
               | RET
               | RETURN
               | SALOAD
               | SASTORE
               | SIPUSH
               | SWAP
               | TABLESWITCH
               | WIDE
               deriving (Eq, Show)
